/*
Find the biggest number that only appears once.

my_numbers
+---+
|num|
+---+
| 8 |
| 8 |
| 3 |
| 3 |
| 1 |
| 4 |
| 5 |
| 6 | 

+---+
|num|
+---+
| 6 |

*/

DROP TABLE MY_NUMBERS;
CREATE TABLE MY_NUMBERS (NUM INT);
TRUNCATE TABLE MY_NUMBERS;
INSERT ALL
INTO MY_NUMBERS (NUM) VALUES ('8')
INTO MY_NUMBERS (NUM) VALUES ('8')
INTO MY_NUMBERS (NUM) VALUES ('3')
INTO MY_NUMBERS (NUM) VALUES ('3')
INTO MY_NUMBERS (NUM) VALUES ('1')
INTO MY_NUMBERS (NUM) VALUES ('4')
INTO MY_NUMBERS (NUM) VALUES ('5')
INTO MY_NUMBERS (NUM) VALUES ('6')
SELECT * FROM DUAL;
SELECT * FROM MY_NUMBERS;

--WRONG
SELECT NUM --MAX(NUM) IS WRONG!
FROM MY_NUMBERS
GROUP BY NUM
HAVING COUNT(NUM) = 1;

--FINAL
SELECT MAX(NUM)
FROM
(
	SELECT NUM
	FROM MY_NUMBERS
	GROUP BY NUM
	HAVING COUNT(NUM) = 1
);